### ISSUE TITLE
Why research queue is empty when opening a technology?

### ISSUE THREAD

**Issue by AqlaSolutions** [npo6ka/FNEI#37]
See https://forums.factorio.com/viewtopic.php?f=23&t=67845

**Comment by npo6ka** [comment]
Thank you for your feedback. Would you please attach your save file here? I will check what could be the problem.

**Comment by npo6ka** [comment]
And tell me please, is it a multiplayer game or a singleplayer?

**Comment by npo6ka** [comment]
Oh, I understand what the problem is. Unfortunately, the mechanics of the game does not allow to open certain technologies in the technology tree, so you have to use workarounds for this. When you play in a single-player game, all research disappears and after the technology tree is closed, they come back again if you have not chosen other research. Unfortunately, otherwise it is impossible to open the technology selected in FNEI gui.

**Comment by npo6ka** [comment]
In the next version of this game, this problem will be fixed:
https://forums.factorio.com/viewtopic.php?f=23&t=67845&p=415114#p415078

**Comment by AqlaSolutions** [comment]
@npo6ka , cool, thx!
